### ISSUE TITLE
Dynamic provisioning of EBS volume to spark executors

### ISSUE THREAD

**Issue by chachampis** [aws/aws-emr-containers-best-practices#26]
Hi, 

in the [storage docs](https://github.com/aws/aws-emr-containers-best-practices/blob/main/content/storage/docs/spark/ebs.md) there is mentioned at the end of the page:

> POINT TO NOTE:
It is not possible to use this dynamic provisioning strategy for EBS to spark executors. It is not possible to mount a new EBS volume to every Spark executor. Instead use a distributed file system like Lustre, EFS, NFS to mount to executors.

Why is this not possible? Is it just not supported yet, or is it just impossible for some other reason? [Spark docs](https://spark.apache.org/docs/latest/running-on-kubernetes.html#local-storage) suggest it can be done. But when I tried the suggested config in an EMR on EKS cluster, the configured serviceaccount for the executor pods did not have the necessary permissions to deal with persistentvolumeclaims.

**Comment by dacort** [comment]
I'm not sure offhand, but it could be because of cross-AZ issues? Note in the static section it mentions:
> Pods running in EKS worker nodes can only attach to the EBS volume provisioned in the same AZ as the EKS worker node.

Maybe @saravanan-sathyamoorthy knows.

**Comment by dalbhanj** [comment]
Hi @chachampis , the issue with permission will be fixed in our next release (6.8). You can see patch for making this work here (https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/permissions-for-pvc.html). I'll close this issue for now. If you have additional issue/question, please open new issue. Thank you!
