### ISSUE TITLE
Using s3 and pex

### ISSUE THREAD

**Issue by 8enmann** [aws/aws-emr-containers-best-practices#3]
I followed [the guide on using pex](https://aws.github.io/aws-emr-containers-best-practices/submit-applications/docs/spark/pyspark/#bundled-as-a-pex-file), but I don't want to mount fsx. I tried including the .pex in --py-files, but the file ended up in a directory like /tmp/spark-56e3c931-97d3-4c15-b175-299b349a0a8f/

How do I specify the path in `spark.pyspark.driver.python`?  I tried using "dep.pex" hoping it'd be in the working directory already, but I got a file not found error. I also tried using the s3 path; same error.

**Comment by masonse** [comment]
Thank you @8enmann for raising this issue, we are looking into this.

**Comment by zeekay18** [comment]
Please has anyone found a solution to this issue

**Comment by saravanan-sathyamoorthy** [comment]
@8enmann @zeekay18 Thanks for your patience. With [Custom pod template feature,](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/pod-templates.html) you can run an init container within the driver and executor pods and make the .pex available to driver and executor containers without the need to use persistent volumes. EMR on EKS [guide on using pex](https://aws.github.io/aws-emr-containers-best-practices/submit-applications/docs/spark/pyspark/#bundled-as-a-pex-file) has been updated with the sample configuration. can you please check if this works for your usecase.

**Comment by 8enmann** [comment]
I switched to my own spark implementation instead of EMR, seems to work fine and I can use my own docker image

**Comment by zeekay18** [comment]
yes, thank you @saravanan-sathyamoorthy. This worked for me
